DOMAIN = "aussie_atis"

AIRPORTS = {
    "YSSY": "Sydney Airport",
    "YMML": "Melbourne Airport",
    "YBBN": "Brisbane Airport",
    "YPPH": "Perth Airport",
    "YPAD": "Adelaide Airport",
    "YBCG": "Gold Coast Airport",
    "YBCS": "Cairns Airport",
    "YSCB": "Canberra Airport",
    "YMHB": "Hobart Airport",
    "YPDN": "Darwin International Airport",
    "YBTL": "Townsville Airport",
    "YMLT": "Launceston Airport",
    "YWLM": "RAAF Williamtown",
    "YBMK": "Mackay Airport",
    "YBSU": "Sunshine Coast Airport",
    "YPKA": "Karratha Airport",
    "YBRK": "Rockhampton Airport",
    "YBAS": "Alice Springs Airport",
    "YPPD": "Port Hedland International Airport",
    "YAMB": "RAAF Amberley",
    "YPED": "RAAF Edinburgh",
    "YPTN": "RAAF Tindal",
    "YMES": "RAAF East Sale",
    "YPEA": "RAAF Pearce",
    "YSRI": "RAAF Richmond",
    "YBSG": "RAAF Scherger",
    "YPLM": "RAAF Learmonth",
    "YCIN": "RAAF Curtin",
    "YGIG": "RAAF Gingin",
    "YGNB": "RAAF Glenbrook",
    "YMPC": "RAAF Williams",
    "YPWR": "RAAF Woomera",
    "YBOK": "Oakey Army Aviation Centre",
    "YSNW": "HMAS Albatross"
}
# const.py placeholder
